package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import model.Product;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import dao.ProductDao;
import javafx.beans.property.SimpleStringProperty;
import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

import javafx.scene.control.ChoiceBox;
import javafx.scene.control.Label;

public class ProductFormController implements Initializable{
	
	private Main m = new Main();
	private ProductDao productDao =  new ProductDao();
	private Product product = null;
	
    @FXML private Label errorLabel;

	@FXML
	private TextField nameField;
	@FXML
	private TextArea descField;
	@FXML
	private TextField priceField;
	@FXML
	private TextField unitField;
	@FXML
	private TextField cityField;
	@FXML
	private ChoiceBox categoryField;
	@FXML
	private Button SubmitBtn;

	// Event Listener on Button[#SubmitBtn].onAction
	@FXML
	public void submitProduct(ActionEvent event) throws IOException {
		// TODO Autogenerated
      float price =Float.parseFloat(priceField.getText());  
      DashboardController dashboardController = new DashboardController();
//	    if(dashboardController.insertProduct(nameField.getText(), descField.getText(),  price, unitField.getText(), cityField.getText(), 2)) {
//            errorLabel.setText("Producted Added Successfully!");
//            errorLabel.setStyle("-fx-text-fill: #1cfd6c;");  
//            dashboardController.dialog.close();
//        }else {
//            errorLabel.setText("Product Name "+nameField.getText()+" Already Exist!");
//           
//        }   
	    
	    if(dashboardController.updateProduct(nameField.getText(), descField.getText(),  price, unitField.getText(), cityField.getText(), 2)) {
    errorLabel.setText("Producted Added Successfully!");
    errorLabel.setStyle("-fx-text-fill: #1cfd6c;");  
    dashboardController.dialog.close();
}else {
    errorLabel.setText("Product Name "+nameField.getText()+" Already Exist!");
   
}   
	}
	
	public void setProduct(Product product){
		nameField.textProperty().bindBidirectional(product.nameProperty());
	  }

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
	}
	
}
